services:
    _defaults:
        public: true

    Oro\Bundle\CampaignBundle\Controller\EmailCampaignController:
        arguments:
            - '@validator'
            - '@translator'
            - '@session'
            - '@form.factory'
            - '@oro_ui.router'
            - '@oro_campaign.email_campaign.form'
            - '@oro_campaign.form.handler.email_campaign'
            - '@oro_campaign.email_campaign.sender.builder'
