parameters:
    # Entities
    oro_marketing_activity.entity.class: Oro\Bundle\MarketingActivityBundle\Entity\MarketingActivity
services:
    oro_marketing_activity.provider.virtual_relation.marketing_activity:
        class: 'Oro\Bundle\MarketingActivityBundle\Provider\MarketingActivityVirtualRelationProvider'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_marketing_list.entity_provider.contact_information'
        tags:
            - { name: oro_entity.virtual_relation_provider, priority: 150 }
