parameters:
    oro_marketing_activity.provider.virtual_relation.marketing_activity.class: Oro\Bundle\MarketingActivityBundle\Provider\MarketingActivityVirtualRelationProvider

services:
    oro_marketing_activity.provider.virtual_relation.marketing_activity:
        class: %oro_marketing_activity.provider.virtual_relation.marketing_activity.class%
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_marketing_list.entity_provider.contact_information'
        tags:
            - { name: oro_entity.virtual_relation_provider, priority: 150 }
    oro_marketing_activity.placeholder.filter:
        class: 'Oro\Bundle\MarketingActivityBundle\Placeholder\PlaceholderFilter'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_marketing_list.entity_provider.contact_information'
    oro_marketing_activity.marketing_activity.manager.api:
        class: 'Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager'
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\MarketingActivityBundle\Entity\MarketingActivity'
            - "@doctrine.orm.entity_manager"
