navigation:
    menu_config:
        items:
            marketing_tab:
                label: 'oro.campaign.menu.marketing_tab.label'
                uri: '#'
                extras:
                    position: 40
                    icon: icon-sitemap
            campaigns_list:
                label: 'oro.campaign.entity_plural_label'
                route: 'oro_campaign_index'
                extras:
                    routes: ['oro_campaign_*']
                    position: 10
            email_campaigns_list:
                label: 'oro.campaign.emailcampaign.entity_plural_label'
                route: 'oro_email_campaign_index'
                extras:
                    routes: ['oro_email_campaign_*']
                    position: 20
            websites_list:
                label: 'oro.tracking.trackingwebsite.entity_plural_label'
                route: 'oro_tracking_website_index'
                extras:
                    routes: ['oro_tracking_*']
                    position: 20
        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            campaigns_list: ~
                            email_campaigns_list: ~
                            websites_list: ~

    titles:
        oro_campaign_index:  ~
        oro_campaign_view:   %%entity.name%%
        oro_campaign_create: oro.ui.create_entity
        oro_campaign_update: %%entity.name%% - Edit

        oro_tracking_website_index: ~

        oro_email_campaign_index:  ~
        oro_email_campaign_view:   %%entity.name%%
        oro_email_campaign_create: oro.ui.create_entity
        oro_email_campaign_update: %%entity.name%% - Edit
