oro_campaign_api:
    resource:     "@OroCampaignBundle/Controller/Api/Rest/CampaignController.php"
    type:         rest

oro_email_campaign_api:
    resource:     "@OroCampaignBundle/Controller/Api/Rest/EmailCampaignController.php"
    type:         rest

oro_email_campaign_template_api:
    resource:     "@OroCampaignBundle/Controller/Api/Rest/EmailTemplateController.php"
    type:         rest
