oro_campaign_bundle:
    resource:     "@OroCampaignBundle/Controller"
    type:         annotation
    prefix:       /

oro_campaign_dashboard:
    resource:     "@OroCampaignBundle/Controller/Dashboard"
    type:         annotation
    prefix:       /dashboard


#
# DEPRECATED OLD REST API ROUTES
#

oro_api_options_emailcampaign_email_templates:
    path: '/api/rest/{version}/emailcampaign/email/templates.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\CampaignBundle\Controller\Api\Rest\EmailTemplateController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1


#
# OLD REST API ROUTES
#

oro_api_get_emailcampaign_email_templates:
    path: '/api/rest/{version}/emailcampaigns/{id}/email/templates.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\CampaignBundle\Controller\Api\Rest\EmailTemplateController::cgetAction'
        _format: json
        version: latest
    requirements:
        id: '\d*'
        _format: json|html
        version: latest|v1
