services:
    Oro\Bundle\TrackingBundle\Command\ImportLogsCommand:
        public: false
        class: Oro\Bundle\TrackingBundle\Command\ImportLogsCommand
        arguments:
            - '@akeneo_batch.job_repository'
            - '@oro_featuretoggle.checker.feature_checker'
            - '@oro_importexport.job_executor'
            - '@oro_config.user'
            - '%kernel.logs_dir%'
        tags:
            - { name: console.command }

    Oro\Bundle\TrackingBundle\Command\TrackCommand:
        public: false
        class: Oro\Bundle\TrackingBundle\Command\TrackCommand
        tags:
            - { name: console.command }
