services:
    _defaults:
        public: true

    Oro\Bundle\TrackingBundle\Controller\TrackingDataController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\TrackingBundle\Controller\TrackingWebsiteController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
