features:
    marketing:
        label: oro.marketing.feature.label
        description: oro.marketing.feature.description
        toggle: oro_marketing.feature_enabled
        routes:
            # marketing list routes
            - 'oro_marketing_list_index'
            - 'oro_marketing_list_view'
            - 'oro_marketing_list_create'
            - 'oro_marketing_list_update'
            - 'oro_api_contact_marketinglist_information_field_type'
            - 'oro_api_entity_marketinglist_contact_information_fields'
            - 'oro_api_delete_marketinglist'
            - 'oro_api_options_marketinglists'
            - 'oro_api_remove_marketinglist_removeditem'
            - 'oro_api_unremove_marketinglist_removeditem'
            - 'oro_api_post_marketinglist_removeditem'
            - 'oro_api_delete_marketinglist_removeditem'
            - 'oro_api_options_marketinglist_removeditems'
            - 'oro_api_unsubscribe_marketinglist_unsubscribeditem'
            - 'oro_api_subscribe_marketinglist_unsubscribeditem'
            - 'oro_api_post_marketinglist_unsubscribeditem'
            - 'oro_api_delete_marketinglist_unsubscribeditem'
            - 'oro_api_options_marketinglist_unsubscribeditems'
            - 'oro_api_post_marketinglist_segment_run'
            - 'oro_api_options_marketinglist_segments'
            - 'oro_api_post_marketinglist_removeditem_deprecated'
            - 'oro_api_post_marketinglist_segment_run_deprecated'
            - 'oro_api_post_marketinglist_unsubscribeditem_deprecated'

            # campaign routes
            - 'oro_campaign_index'
            - 'oro_campaign_create'
            - 'oro_campaign_update'
            - 'oro_campaign_view'
            - 'oro_campaign_event_plot'
            - 'oro_email_campaign_index'
            - 'oro_email_campaign_create'
            - 'oro_email_campaign_update'
            - 'oro_email_campaign_view'
            - 'oro_email_campaign_send'
            - 'oro_campaign_dashboard_campaigns_leads_chart'
            - 'oro_campaign_dashboard_campaigns_opportunity_chart'
            - 'oro_campaign_dashboard_campaigns_by_close_revenue_chart'
            - 'oro_api_delete_campaign'
            - 'oro_api_options_campaigns'
            - 'oro_api_delete_emailcampaign'
            - 'oro_api_options_emailcampaigns'
            - 'oro_api_get_emailcampaign_email_templates'
            - 'oro_api_options_emailcampaign_email_templates'

            # tracking routes
            - 'oro_tracking_data_create'
            - 'oro_tracking_website_index'
            - 'oro_tracking_website_create'
            - 'oro_tracking_website_update'
            - 'oro_tracking_website_view'
            - 'oro_api_delete_tracking_website'
            - 'oro_api_options_tracking_websites'
            - 'oro_magento_widget_tracking_events'
        dashboard_widgets:
            - 'campaigns_leads'
            - 'campaigns_opportunity'
            - 'campaigns_by_close_revenue'
        field_configs:
            - 'campaign'
