security:
    firewalls:
        tracking_data:
            pattern:   ^/tracking/data/create
            provider:  chain_provider
            anonymous: true
            logout_on_user_change: true
assetic:
    assets:
        tracking_lib:
            inputs:
                - 'bundles/orotracking/lib/tracking.php'
            output: 'tracking.php'
