oro_tracking:
    resource:     "@OroTrackingBundle/Controller"
    type:         annotation
    prefix:       /


#
# DEPRECATED OLD REST API ROUTES
#

oro_api_options_tracking_websites:
    path: '/api/rest/{version}/tracking/websites.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\TrackingBundle\Controller\Api\Rest\TrackingWebsiteController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1


#
# OLD REST API ROUTES
#

oro_api_delete_tracking_website:
    path: '/api/rest/{version}/trackings/{id}/website.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\TrackingBundle\Controller\Api\Rest\TrackingWebsiteController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1
