placeholders:
    placeholders:
        view_content_data_marketing_activities_summary:
            items:
                view_oro_marketing_activity_summary: ~

    items:
        view_oro_marketing_activity_summary:
            applicable: "@oro_marketing_activity.placeholder.filter->isSummaryApplicable($campaignId$)"
            action: OroMarketingActivityBundle:MarketingActivity:summary
