placeholders:
    placeholders:
        view_content_data_marketing_activities_summary:
            items:
                view_oro_marketing_activity_summary: ~
        view_content_data_marketing_activities:
            items:
                view_oro_marketing_activity_list: ~

    items:
        view_oro_marketing_activity_summary:
            applicable: "@oro_marketing_activity.placeholder.filter->isSummaryApplicable($campaignId$)"
            action: Oro\Bundle\MarketingActivityBundle\Controller\MarketingActivityController::summaryAction
            acl: oro_marketing_activity_view
        view_oro_marketing_activity_list:
            applicable: "@oro_marketing_activity.placeholder.filter->isApplicable($entity$)"
            template: '@@OroMarketingActivity/MarketingActivity/marketingActivitiesSection.html.twig'
            acl: oro_marketing_activity_view
